@startuml Hello

''' ENUMERATIONS '''
enum Number {
    one 
    two
    three
    four
    five
    six
    seven
    eight
    nine
}

enum Color {
    red
    green
    blue
    purple
    yellow
    brown
}

enum Version {
    Legacy
    Tactic
}

enum Side {
    none
    s1
    s2
}

enum CombinationType {
	sum
	straight
	flush
	three_of_a_kind
	straight_flush
}


''' CLASSES '''


''' HERITAGES '''
Controller <|-- TacticController

Player <|-- PlayerAIRandom

Card <|-- Clan
Card <|-- Tactical

Tactical <|-- Elite
Tactical <|-- CombatMode
Tactical <|-- Ruses


''' RELATIONS '''


Controller "1" *-- "1" Game
Controller "1" *-- "1" Board
Controller "1" *-- "1|2" Deck
Controller "1" *-- "2" Player
TacticController "1" *-- "1" Discard
Supervisor "1" *-- "1"Controller 
Game "1" *-- "54|64" Card
Board "1" *-- "9" Stone
Player "1" *-- "1" Hand

Card "*" --o "1" Discard
Card "*" --o "1" Deck
Card "*" --o Board
Card "6|7" --o "1" Hand

@enduml